[pytest]
#addopts = -v --html=Reports/HTML_Report.html 
markers=
    great: used for tests that use the greater than operator
    less: used for tests that use the less than operator
    activity: used to mark tests as activities