-- CREATE THE SALESMAN TABLE
CREATE TABLE SALESMAN(
SALESMAN_ID INT PRIMARY KEY, 
_NAME VARCHAR(20) NOT NULL, 
SALESMAN_CITY VARCHAR(20), 
COMMISSION INT
);

-- TO VIEW THE SCHEMA OF THE TABLE
DESCRIBE SALESMAN;

INSERT INTO SALESMAN(SALESMAN_ID, SALESMAN_NAME, SALESMAN_CITY, COMMISSION) VALUES (5001,'JAMES HOOG','NEW YORK',15);
INSERT INTO SALESMAN(SALESMAN_ID, SALESMAN_NAME, SALESMAN_CITY, COMMISSION) VALUES (5002,'NAIL KNITE','PARIS',13);
INSERT INTO SALESMAN(SALESMAN_ID, SALESMAN_NAME, SALESMAN_CITY, COMMISSION) VALUES (5005,'PIT ALEX','LONDON',11);
INSERT INTO SALESMAN(SALESMAN_ID, SALESMAN_NAME, SALESMAN_CITY, COMMISSION) VALUES (5006,'MCLYON','PARIS',14);
INSERT INTO SALESMAN(SALESMAN_ID, SALESMAN_NAME, SALESMAN_CITY, COMMISSION) VALUES (5007,'PAUL ADAM','ROME',13);
INSERT INTO SALESMAN(SALESMAN_ID, SALESMAN_NAME, SALESMAN_CITY, COMMISSION) VALUES (5003,'LAUSON HEN','SAN JOSE',12);

-- ONE MORE WAY
-- INSERT ALL 
-- INTO SALESMAN VALUES('5001','JAMES HOOG','NEW YORK','15')
-- INTO SALESMAN VALUES ('5002','NAIL KNITE','PARIS','13')
-- ETC
-- SELECT 1 FROM DUAL;

-- SHOW SALESMAN_ID AND CITY
SELECT SALESMAN_ID, SALESMAN_CITY, COMMISSION FROM SALESMAN;

-- SHOW THE ONES FROM PARIS
SELECT * FROM SALESMAN WHERE SALESMAN_CITY = 'Paris';

-- SHOW SALESMAN ID AND COMMISSION OF PAUL ADAM
SELECT SALESMAN_ID, COMMISSION FROM SALESMAN WHERE SALESMAN_NAME = 'Paul Adam';

-- Show data from the salesman_id and salesman_city columns
SELECT salesman_id, salesman_city FROM salesman;
-- Show data of salesman from Paris
SELECT * FROM salesman WHERE salesman_city='Paris';
-- Show salesman_id and commission of Paul Adam
SELECT salesman_id, commission FROM salesman WHERE salesman_name='Paul Adam';

-- Add a grade column to the salesman table
ALTER TABLE salesman ADD (grade int);
-- Set the grade columns values to 100 for all the rows
UPDATE salesman SET grade=100;
-- Update the grade score of salesmen from Rome to 200.
UPDATE salesman SET grade=200 WHERE salesman_city='Rome';
-- Update the grade score of James Hoog to 300.
UPDATE salesman SET grade=300 WHERE salesman_name='James Hoog';
-- Update the name McLyon to Pierre.
UPDATE salesman SET salesman_name='Pierre' WHERE salesman_name='McLyon';

SELECT * FROM SALESMAN;